name: CI Build

on:
  push:
    branches:
      - '**'
  workflow_dispatch:

jobs:
  build-sd-image:
    # Use GitHub-hosted runner instead of self-hosted
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: arm64
      
      - name: Setup Nix
        uses: cachix/install-nix-action@v20
        with:
          nix_path: nixpkgs=/nix/var/nix/profiles/per-user/root/channels/nixpkgs
          extra_nix_config: |
            experimental-features = nix-command flakes
            system-features = arm-linux aarch64-linux
            extra-platforms = aarch64-linux arm-linux
      
      - name: Configure Nix for Cross-compilation
        run: |
              echo "extra-platforms = aarch64-linux arm-linux" | sudo tee -a /etc/nix/nix.conf
              sudo systemctl restart nix-daemon
      
      - name: Build SD Image
        run: |
              nix build \
                --option system aarch64-linux \
                --no-update-lock-file \
                '.#nixosConfigurations.rpi-example.config.system.build.sdImage'
              mkdir -p artifacts
              cp -r -L /nix/store/*nixos-sd-image-*.img artifacts/
              sha256sum artifacts/*nixos-sd-image-*.img > artifacts/SHA256SUMS
      
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: sd-image-${{ github.sha }}
          path: |
                artifacts/nixos-sd-image-*.img
                artifacts/SHA256SUMS
