name: CI Build

on:
  push:
    branches:
      - '**'  # Triggers on all branches
  workflow_dispatch:  # Allows manual triggering

jobs:
  build-sd-image:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout
      - name: Checkout Repository
        uses: actions/checkout@v4  # ✓ Latest version

      # Step 2: QEMU Setup
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3  # ✓ Latest version
        with:
          platforms: arm64  # ✓ Correct for RPi builds

      # Step 3: Nix Setup
      - name: Setup Nix
        uses: cachix/install-nix-action@v20  # ✓ Latest version
        with:
          nix_path: nixpkgs=/nix/var/nix/profiles/per-user/root/channels/nixpkgs
          extra_nix_config: |
            experimental-features = nix-command flakes
            system-features = big-parallel kvm nixos-test benchmark
            extra-platforms = aarch64-linux

      # Step 4: Nix Configuration
      - name: Configure Nix and Sudo
        run: |
          sudo mkdir -p /etc/nix
          cat << EOF | sudo tee /etc/nix/nix.conf
          experimental-features = nix-command flakes
          system-features = big-parallel kvm nixos-test benchmark
          extra-platforms = aarch64-linux
          EOF
          
          echo "root ALL=(ALL:ALL) ALL" | sudo tee /etc/sudoers.d/root
          sudo chmod 440 /etc/sudoers.d/root

          sudo systemctl restart nix-daemon

      # Step 5: Build Process
      - name: Build SD Image
        run: |
          nix build \
            --option system aarch64-linux \
            --option extra-system-features "big-parallel" \
            --option system-features "big-parallel kvm nixos-test benchmark" \
            --no-update-lock-file \
            '.#nixosConfigurations.rpi-example.config.system.build.sdImage'
          mkdir -p artifacts
          sudo cp -r -L /nix/store/*nixos-sd-image-*.img artifacts/

      # Step 6: Artifact Upload
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4  # ✓ Latest version
        with:
          name: sd-image-${{ github.sha }}
          path: |
            artifacts/nixos-sd-image-*.img